### ISSUE TITLE
Where is the makefile

### ISSUE THREAD

**Issue by caecos** [VincentCusson/MUMT307_finalProject#1]
Hi, I will be glad to try your modules but how can I compile the sources without the makefile? I use MSYS2 on Windows...

**Comment by VincentCusson** [comment]
I just added the Makefile I used on macOS. Still new to this so I am not sure how it would work in MSYS2. Tell me if you manage to compile the sources.

**Comment by caecos** [comment]
J'essaie dans l'heure...

**Comment by caecos** [comment]
It works perfectly...merci!
